const getRandomItem = (arr) => {
  var index = Math.floor(Math.random() * arr.length);
  return arr[index];
};

const getRandomEmoji = () => {
  return getRandomItem([
    "😀",
    "😊",
    "😍",
    "😎",
    "🤩",
    "🥳",
    "🤗",
    "🤔",
    "😄",
    "😘",
    "🌞",
    "🌈",
    "🌻",
    "🌺",
    "🍕",
    "🍦",
    "🎉",
    "🎈",
    "✨",
    "🎁",
    "🐶",
    "🐱",
    "🐼",
    "🐬",
    "🐦",
    "🐝",
    "🐢",
    "🐞",
    "🦄",
    "🦋",
    "🍔",
    "🍓",
    "🍩",
    "🍿",
    "🍍",
    "🍄",
    "🌸",
    "🌼",
    "🌙",
    "⭐️",
    "🎵",
    "🎮",
    "📚",
    "🎨",
    "🎥",
    "📷",
    "🔥",
    "⚽️",
    "🚀",
    "🚲",
    "⌚️",
    "📱",
    "💻",
    "🎧",
    "📺",
    "🕹️",
    "📸",
  ]);
};

const head = (title, description, domainName, faq, amp) => {
  return `<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>${title}</title>
    ${
      description === domainName + " Website Description" || description === ""
        ? ""
        : '<meta name="description" content="' + description + '" />'
    }
    <link rel="canonical" href="https://${domainName}/" />
    ${
      amp === true
        ? `<link rel="amphtml" href="https://${domainName}/amp.html">`
        : ""
    }
    <meta name="generator" content="OOWG${
      Math.floor(Math.random() * (99999 - 10000 + 1)) + 10000
    }"/>
    <script type = "application/ld+json">
    {
    "@context": "http://www.schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "item": {
            "@type": "WebPage",
            "@id": "/",
            "name": "${getRandomItem([
              "webpage",
              "site",
              "portal",
              "homepage",
              "web address",
              "URL",
              "web property",
              "internet site",
              "web platform",
              "net location",
              "online presence",
              "web destination",
              "online platform",
              "web resource",
              "digital space",
              "web space",
              "web spot",
              "internet page",
              "internet destination",
              "digital site",
              "web project",
              "web location",
              "internet platform",
              "web hub",
              "internet hub",
              "online site",
              "net portal",
              "digital portal",
              "web portal",
              "online portal",
            ])}"
        }
    }, {
        "@type": "ListItem",
        "position": 2,
        "item": {
            "@type": "WebPage",
            "@id": "/#h1_1",
            "name": "${getRandomItem([
              "☀",
              "☁",
              "☂",
              "☃",
              "☄",
              "☎",
              "☑",
              "☔",
              "☕",
              "☘",
              "☠",
              "☢",
              "☣",
              "☮",
              "☯",
              "☹",
              "☺",
              "♀",
              "♂",
              "♟",
              "⚡️",
              "💸",
              "💡",
              "🔥",
              "🎈",
              "🎉",
              "🏠",
              "🐶",
              "👍",
              "🍎",
              "🍕",
              "🚀",
              "🚗",
              "🚨",
              "⚽",
              "⛄",
              "🌎",
              "🌙",
              "🌟",
              "🌱",
              "🌸",
              "🌹",
              "🍀",
              "🍁",
              "🍂",
              "🍃",
              "🎄",
              "🎃",
              "🏂",
              "🏊",
              "🏋️‍♂️",
              "🏄",
              "🐱",
              "🐼",
              "👓",
              "👖",
              "💍",
              "📱",
              "📷",
              "🔑",
            ])}${getRandomItem([
    "☀",
    "☁",
    "☂",
    "☃",
    "☄",
    "☎",
    "☑",
    "☔",
    "☕",
    "☘",
    "☠",
    "☢",
    "☣",
    "☮",
    "☯",
    "☹",
    "☺",
    "♀",
    "♂",
    "♟",
    "⚡️",
    "💸",
    "💡",
    "🔥",
    "🎈",
    "🎉",
    "🏠",
    "🐶",
    "👍",
    "🍎",
    "🍕",
    "🚀",
    "🚗",
    "🚨",
    "⚽",
    "⛄",
    "🌎",
    "🌙",
    "🌟",
    "🌱",
    "🌸",
    "🌹",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🎄",
    "🎃",
    "🏂",
    "🏊",
    "🏋️‍♂️",
    "🏄",
    "🐱",
    "🐼",
    "👓",
    "👖",
    "💍",
    "📱",
    "📷",
    "🔑",
  ])}${getRandomItem([
    "☀",
    "☁",
    "☂",
    "☃",
    "☄",
    "☎",
    "☑",
    "☔",
    "☕",
    "☘",
    "☠",
    "☢",
    "☣",
    "☮",
    "☯",
    "☹",
    "☺",
    "♀",
    "♂",
    "♟",
    "⚡️",
    "💸",
    "💡",
    "🔥",
    "🎈",
    "🎉",
    "🏠",
    "🐶",
    "👍",
    "🍎",
    "🍕",
    "🚀",
    "🚗",
    "🚨",
    "⚽",
    "⛄",
    "🌎",
    "🌙",
    "🌟",
    "🌱",
    "🌸",
    "🌹",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🎄",
    "🎃",
    "🏂",
    "🏊",
    "🏋️‍♂️",
    "🏄",
    "🐱",
    "🐼",
    "👓",
    "👖",
    "💍",
    "📱",
    "📷",
    "🔑",
  ])} ${getRandomItem([
    "Discover",
    "Explore",
    "Reveal",
    "Unlock",
    "Now!",
    "Join",
    "Claim",
    "Try Free",
    "Get Bonus",
    "Sign Up",
    "Try Now",
    "Exclusive",
    "Start",
    "Dive In",
    "Cashback",
    "Find Out",
    "Hurry",
    "Limited",
    "Reward",
    "Win Big",
  ])} ${getRandomItem([
    "☀",
    "☁",
    "☂",
    "☃",
    "☄",
    "☎",
    "☑",
    "☔",
    "☕",
    "☘",
    "☠",
    "☢",
    "☣",
    "☮",
    "☯",
    "☹",
    "☺",
    "♀",
    "♂",
    "♟",
    "⚡️",
    "💸",
    "💡",
    "🔥",
    "🎈",
    "🎉",
    "🏠",
    "🐶",
    "👍",
    "🍎",
    "🍕",
    "🚀",
    "🚗",
    "🚨",
    "⚽",
    "⛄",
    "🌎",
    "🌙",
    "🌟",
    "🌱",
    "🌸",
    "🌹",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🎄",
    "🎃",
    "🏂",
    "🏊",
    "🏋️‍♂️",
    "🏄",
    "🐱",
    "🐼",
    "👓",
    "👖",
    "💍",
    "📱",
    "📷",
    "🔑",
  ])}${getRandomItem([
    "☀",
    "☁",
    "☂",
    "☃",
    "☄",
    "☎",
    "☑",
    "☔",
    "☕",
    "☘",
    "☠",
    "☢",
    "☣",
    "☮",
    "☯",
    "☹",
    "☺",
    "♀",
    "♂",
    "♟",
    "⚡️",
    "💸",
    "💡",
    "🔥",
    "🎈",
    "🎉",
    "🏠",
    "🐶",
    "👍",
    "🍎",
    "🍕",
    "🚀",
    "🚗",
    "🚨",
    "⚽",
    "⛄",
    "🌎",
    "🌙",
    "🌟",
    "🌱",
    "🌸",
    "🌹",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🎄",
    "🎃",
    "🏂",
    "🏊",
    "🏋️‍♂️",
    "🏄",
    "🐱",
    "🐼",
    "👓",
    "👖",
    "💍",
    "📱",
    "📷",
    "🔑",
  ])}${getRandomItem([
    "☀",
    "☁",
    "☂",
    "☃",
    "☄",
    "☎",
    "☑",
    "☔",
    "☕",
    "☘",
    "☠",
    "☢",
    "☣",
    "☮",
    "☯",
    "☹",
    "☺",
    "♀",
    "♂",
    "♟",
    "⚡️",
    "💸",
    "💡",
    "🔥",
    "🎈",
    "🎉",
    "🏠",
    "🐶",
    "👍",
    "🍎",
    "🍕",
    "🚀",
    "🚗",
    "🚨",
    "⚽",
    "⛄",
    "🌎",
    "🌙",
    "🌟",
    "🌱",
    "🌸",
    "🌹",
    "🍀",
    "🍁",
    "🍂",
    "🍃",
    "🎄",
    "🎃",
    "🏂",
    "🏊",
    "🏋️‍♂️",
    "🏄",
    "🐱",
    "🐼",
    "👓",
    "👖",
    "💍",
    "📱",
    "📷",
    "🔑",
  ])}"
        }
    }]
    }
    </script>
    ${
      faq.length > 0
        ? `<script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [${faq.map((faqItem) => {
        return `{
        "@type": "Question",
        "name": "${getRandomEmoji()} ${faqItem[0]}",
      "acceptedAnswer": {
      "@type": "Answer",
      "text": "${getRandomEmoji()} ${faqItem[1]}"
    }
    }`;
      })}]
    }
  </script>`
        : ""
    }
<!--    <meta name="robots" content="nofollow noarchive nositelinkssearchbox nosnippet notranslate max-snippet:[0]">-->
    <meta name="robots" content="nofollow noarchive notranslate">
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>`;
};

export default head;
